// Generated by CodiumAI

import { expect } from "chai";
import Color from "../classes/Color";

/*
Code Analysis

Main functionalities:
The Color class represents a color and provides methods to convert it between different formats. It can be created from RGB or hex values, and can be converted to RGB, hex, or a string representation. It also allows checking if the color is transparent.

Methods:
- constructor: creates a new Color instance with optional RGB and alpha values
- get/set r, g, b, a: getters and setters for the color components, with validation for values between 0 and 255 (for RGB) or 0 and 100 (for alpha)
- static createFromHex(hex): creates a new Color instance from a hex string, with optional alpha value
- static isValidHex(hex): checks if a hex string is valid
- isTransparent(): checks if the color is transparent (alpha value of 0)
- toRgb(): returns the color as an RGB or RGBA string
- toHex(): returns the color as a hex string
- toString(): returns the color as a string (same as toRgb())
- toJSON(): returns the color as a hex string (used for JSON serialization)

Fields:
- _r, _g, _b, _a: the color components, with optional alpha value
*/

describe("Color_class", () => {
    // Tests that a Color object can be created with valid RGB values.
    it("test_create_color_with_valid_rgb_values", () => {
        const color = new Color(100, 150, 200);
        expect(color.r).equal(100);
        expect(color.g).equal(150);
        expect(color.b).equal(200);
    });

    // Tests that a Color object can be created with valid RGBA values.
    it("test_create_color_with_valid_rgba_values", () => {
        const color = new Color(100, 150, 200, 50);
        expect(color.r).equal(100);
        expect(color.g).equal(150);
        expect(color.b).equal(200);
        expect(color.a).equal(50);
    });

    // Tests that the RGB values of a Color object can be retrieved.
    it("test_get_rgb_values", () => {
        const color = new Color(100, 150, 200);
        expect(color.toRgb()).equal("rgb(100,150,200)");
    });

    // Tests that the RGBA values of a Color object can be retrieved.
    it("test_get_rgba_values", () => {
        const color = new Color(100, 150, 200, 50);
        expect(color.toRgb()).equal("rgba(100,150,200,50)");
    });

    // Tests that a Color object can be converted to a hex string.
    it("test_convert_to_hex_string", () => {
        const color = new Color(100, 150, 200);
        expect(color.toHex()).equal("#6496c8ff");
    });

    // Tests that a Color object can be checked for transparency.
    it("test_check_if_color_is_transparent", () => {
        const color1 = new Color(100, 150, 200);
        const color2 = new Color(100, 150, 200, 0);
        expect(color1.isTransparent()).equal(false);
        expect(color2.isTransparent()).equal(true);
    });
});
