// Generated by CodiumAI

import { expect } from "vitest";
import Midi from "@/services/classes/Midi";
import { Output } from "webmidi";
import Outboard from "@/services/classes/Outboard";
import { MessageType } from "@/services/types/devices";

/*
Code Analysis

Main functionalities:
The Midi class is a concrete implementation of the AbstractComunicator class and implements the IComunicatorInterface interface. It provides functionality for sending MIDI messages through WebMidi, as well as receiving and handling MIDI messages. It also allows for enabling and disabling MIDI inputs and outputs.

Methods:
- init(): a static method that initializes WebMidi and returns a new instance of the Midi class with the specified inputs, outputs, and disabled devices.
- isSysexEnabled(): a method that returns a boolean indicating whether sysex is enabled for the WebMidi interface.
- send(): a method that sends a MIDI message through the specified output to the specified channel, with the specified message type, note, and velocity. It also logs the message to the console.
- onMIDIMessage(): a static method that handles incoming MIDI messages and logs them to the console.

Fields:
- _inputs: an array of Input objects representing the available MIDI inputs.
- _outputs: an array of Output objects representing the available MIDI outputs.
- _disabled: an array of strings representing the IDs of disabled MIDI devices.
*/

describe("Midi_class", () => {
    // Tests that WebMidi is enabled successfully and a new instance of Midi is returned.
    it("test_init_success", async () => {
        const midi = await Midi.init();
        expect(midi).toBeInstanceOf(Midi);
    });

    // Tests that a control change message is sent successfully through the specified output.
    it("test_send_control_change", () => {
        const output = new Output("testOutput", true);
        const midi = new Midi([], [output]);
        const outboard = new Outboard({
            id: "testOutboard",
            label: "Test Outboard",
            backgroundColor: "#000000",
            panelColor: "#FFFFFF",
            borderColor: "#CCCCCC",
            controllers: {},
        });
        const result = midi.send(output, 1, MessageType.CONTROLCHANGE, 1, 127, outboard);
        expect(result).toBe(true);
    });

    // Tests that an error is thrown when an invalid messageType is passed to send method.
    it("test_send_invalid_message_type", () => {
        const output = new Output("testOutput", true);
        const midi = new Midi([], [output]);
        const outboard = new Outboard({
            id: "testOutboard",
            label: "Test Outboard",
            backgroundColor: "#000000",
            panelColor: "#FFFFFF",
            borderColor: "#CCCCCC",
            controllers: {},
        });
        expect(() => midi.send(output, 1, "invalidMessageType", 1, 127, outboard)).toThrowError("MessageType invalidMessageType not handled");
    });

    // Tests that an error is thrown when an invalid output is passed to send method.
    it("test_send_invalid_output", () => {
        const output = new Output("testOutput", true);
        const midi = new Midi([], [output]);
        const outboard = new Outboard({
            id: "testOutboard",
            label: "Test Outboard",
            backgroundColor: "#000000",
            panelColor: "#FFFFFF",
            borderColor: "#CCCCCC",
            controllers: {},
        });
        expect(() => midi.send(new Output("invalidOutput", true), 1, MessageType.CONTROLCHANGE, 1, 127, outboard)).toThrowError();
    });

    // Tests that isActive method returns correct boolean value for a given id.
    it("test_is_active", () => {
        const input = new Input("testInput", true);
        const midi = new Midi([input], []);
        expect(midi.isActive("testInput")).toBe(true);
        midi.disable("testInput");
        expect(midi.isActive("testInput")).toBe(false);
        midi.enable("testInput");
        expect(midi.isActive("testInput")).toBe(true);
    });

    // Tests that a program change message is sent successfully through the specified output.
    it("test_send_program_change", () => {
        const output = new Output("testOutput", true);
        const midi = new Midi([], [output]);
        const outboard = new Outboard({
            id: "testOutboard",
            label: "Test Outboard",
            backgroundColor: "#000000",
            panelColor: "#FFFFFF",
            borderColor: "#CCCCCC",
            controllers: {},
        });
        const result = midi.send(output, 1, MessageType.PROGRAMCHANGE, 1, 127, outboard);
        expect(result).toBe(true);
    });
});

