// Generated by CodiumAI

import { expect } from "vitest";
import Outboard from "../classes/Outboard";
import type { IControllerConfigs, IDeviceConfig } from "../types/devices";

/*
Code Analysis

Main functionalities:
The Outboard class represents a device configuration for an external MIDI controller. It implements the IDeviceConfig interface and provides methods for managing the device's properties and controllers. The class also includes methods for adding and deleting controllers, as well as converting the device configuration to JSON format.

Methods:
- constructor(config: IDeviceConfig): creates a new Outboard instance with the specified configuration
- addController(controller: IControllerConfigs): adds a new controller to the device's list of controllers
- deleteController(controller: IControllerConfigs): removes a controller from the device's list of controllers
- toJSON(): converts the device configuration to JSON format

Fields:
- _id: the device's unique identifier
- _label: the device's label
- _backgroundColor: the device's background color
- _panelColor: the device's panel color
- _borderColor: the device's border color
- _borderSize: the device's border size
- _hasMultiSelection: whether the device supports multi-selection
- _category: the device's category
- _style: the device's rotary style
- _logo: the device's logo
- _controllers: the device's list of controllers
- _channel: the device's MIDI channel
- _output: the device's MIDI output interface
- stock: whether the device is a stock device
- originalConfigs: a frozen copy of the device's original configuration
- key: a unique key generated from the device's ID and the current timestamp
*/

describe("Outboard_class", () => {
    let deviceConfig: IDeviceConfig;

    beforeEach(() => {
        // Arrange
        deviceConfig = {
            id: "test",
            label: "Test Outboard",
            backgroundColor: "#FFFFFF",
            stock: false,
            controllers: {
                lcds: [{ type: "LCD", label: "LCD 1", message: "programchange", minValue: 1, maxValue: 100 }],
                toggles: [{ type: "TOGGLE", label: "Toggle 1", message: "controlchange", note: 1, minValue: 0, maxValue: 127 }],
                rotaries: [{ type: "ROTARY", label: "Rotary 1", message: "controlchange", note: 2, minValue: 0, maxValue: 30 }],
            },
        };
    });

    // Tests that an Outboard instance can be created with a valid IDeviceConfig input.
    it("test_create_outboard_instance_with_valid_config", () => {
        const outboard = new Outboard(deviceConfig);

        // Assert
        expect(outboard).instanceOf(Outboard);
        expect(outboard.id).equal(deviceConfig.id);
        expect(outboard.label).equal(deviceConfig.label);
        expect(outboard.backgroundColor.toHex()).equal("#ffffffff");
        expect(outboard.stock).equal(deviceConfig.stock);
        expect(outboard.controllers).to.deep.equal(deviceConfig.controllers);
    });

    it("test_set_stock_device_property", () => {
        // Act
        const outboard = new Outboard({ ...deviceConfig, stock: true });

        // Assert
        expect(() => (outboard.backgroundColor = "#000000")).throw();
    });

    // Tests that properties of an Outboard instance can be set and retrieved correctly.
    it("test_set_and_get_properties", () => {
        const outboard = new Outboard(deviceConfig);

        // Act
        outboard.id = "newId";
        outboard.label = "New Label";
        outboard.backgroundColor = "#000000";
        const newController: IControllerConfigs = { type: "LCD", label: "test", message: "controlchange" };

        // Assert
        expect(outboard.id).equal("newId");
        expect(outboard.label).equal("New Label");
        expect(outboard.backgroundColor.toHex()).equal("#000000ff");
        outboard.addController(newController);
        expect(outboard.controllers.lcds[outboard.controllers.lcds.length - 1]).equal(newController);
        outboard.deleteController(newController);
        expect(outboard.controllers.lcds.length).equal(1);
    });

    // Tests that setting borderSize to 0 throws an error.
    it("test_set_border_size_minor_than_zero", () => {
        // Act
        const outboard = new Outboard(deviceConfig);

        // Assert
        expect(() => (outboard.borderSize = -1)).throw();
    });

    // Tests that adding a controller with a label that already exists throws an error.
    it("test_add_controller_with_existing_label", () => {
        // Act
        const outboard = new Outboard(deviceConfig);
        const newController: IControllerConfigs = { type: "LCD", label: "LCD 1", message: "controlchange" };

        // Assert
        expect(() => outboard.addController(newController)).throw();
    });

    // Tests that deleting a controller that does not exist throws an error.
    it("test_delete_nonexistent_controller", () => {
        // Act
        const outboard = new Outboard(deviceConfig);
        const nonexistentController: IControllerConfigs = { type: "LCD", label: "test2", message: "controlchange" };

        // Assert
        expect(() => outboard.deleteController(nonexistentController)).throw();
    });

    it("test_outboard_tojson_returns_equivalent_of_starting_configs", () => {
        // Act
        const outboard = new Outboard(deviceConfig);
        const json = outboard.toJSON();

        // Assert
        expect(json).to.deep.equal({
            id: "test",
            label: "Test Outboard",
            backgroundColor: "#ffffffff",
            borderColor: "#00000000",
            borderSize: 0,
            category: "uncategorized",
            stock: false,
            logo: undefined,
            panelColor: "#00000000",
            style: "dark",
            controllers: {
                lcds: [
                    {
                        label: "LCD 1",
                        maxValue: 100,
                        message: "programchange",
                        minValue: 1,
                        type: "LCD",
                    },
                ],
                toggles: [
                    {
                        label: "Toggle 1",
                        maxValue: 127,
                        message: "controlchange",
                        minValue: 0,
                        note: 1,
                        type: "TOGGLE",
                    },
                ],
                rotaries: [
                    {
                        label: "Rotary 1",
                        maxValue: 30,
                        message: "controlchange",
                        minValue: 0,
                        note: 2,
                        type: "ROTARY",
                    },
                ],
            },
        });
    });
});
