import type { IDeviceConfig } from "@/services/types/devices";

const configs: IDeviceConfig[] = [
    {
        channel: 1,
        id: "piranha",
        label: "Rocktron Piranha",
        backgroundColor: "#ce4d5f",
        panelColor: "transparent",
        borderColor: "transparent",
        stock: true,
        category: "amps",
        controllers: [
            {
                label: "preset",
                type: "LCD",
                message: "PC",
                minValue: 1,
                maxValue: 98,
            },
            // { label: "data", type: "LCD", message: false, label: "value" },
            {
                label: "fx",
                note: 11,
                type: "TOGGLE",
                message: "CC",
            },
            {
                label: "cc mode",
                note: 50,
                type: "TOGGLE",
                message: "CC",
            }, //continuous controller mode
            {
                label: "clean dist",
                note: 11,
                type: "TOGGLE",
                message: "CC",
            },
            {
                label: "classic modern",
                note: 12,
                type: "TOGGLE",
                message: "CC",
            },
            {
                label: "bass",
                note: 18,
                type: "ROTARY",
                message: "CC",
            },
            {
                label: "mid",
                note: 19,
                type: "ROTARY",
                message: "CC",
            },
            {
                label: "mid freq",
                note: 20,
                type: "ROTARY",
                message: "CC",
            },
            {
                label: "treble",
                note: 21,
                type: "ROTARY",
                message: "CC",
            },
            {
                label: "gain",
                note: 22,
                type: "ROTARY",
                message: "CC",
            },
            {
                label: "volume",
                note: 22,
                type: "ROTARY",
                message: "CC",
            },
        ],
    },
    {
        channel: 2,
        id: "jmp1",
        label: "Marshall JMP-1",
        backgroundColor: "#d6bd7d",
        panelColor: "#111111",
        borderColor: "transparent",
        stock: true,
        category: "amps",
        controllers: [
            { label: "patch", type: "LCD", message: "PC", minValue: 1, maxValue: 100 },
            // { label: "data", type: "LCD", message: false },
            { label: "fx", note: 11, type: "TOGGLE", message: "CC" },
            {
                note: 11,
                type: "TOGGLE",
                message: "CC",
                label: "clean1 clean2",
            },
            {
                note: 12,
                type: "TOGGLE",
                message: "CC",
                label: "dist1 dist2",
            },
            { label: "volume", note: 22, type: "ROTARY", message: "CC" },
            { label: "gain", note: 22, type: "ROTARY", message: "CC" },
            { label: "bass", note: 18, type: "ROTARY", message: "CC" },
            { label: "mid", note: 19, type: "ROTARY", message: "CC" },
            {
                note: 21,
                type: "ROTARY",
                message: "CC",
                label: "treble",
            },
            {
                note: 21,
                type: "ROTARY",
                message: "CC",
                label: "presence",
            },
        ],
    },
    {
        channel: 3,
        id: "gp3",
        label: "VHT GP-3 Valvulator",
        backgroundColor: "transparent",
        panelColor: "transparent",
        borderColor: "#9c9c9c",
        borderSize: 1,
        stock: true,
        category: "amps",
        controllers: [
            // { label: "data", type: "LCD", message: false },
            { label: "clean", note: 11, type: "TOGGLE", message: "CC", group: 1 },
            { label: "rhythm", note: 12, type: "TOGGLE", message: "CC", group: 1 },
            { label: "lead", note: 12, type: "TOGGLE", message: "CC", group: 1 },
            { label: "brite", note: 12, type: "TOGGLE", message: "CC", group: 2 },
            { label: "fat", note: 12, type: "TOGGLE", message: "CC", group: 2 },
            { label: "boost", note: 12, type: "TOGGLE", message: "CC", group: 2 },
            { label: "fx", note: 11, type: "TOGGLE", message: "CC", group: 2 },
            { label: "eq", note: 22, type: "TOGGLE", message: "CC", group: 2 },
        ],
    },
    {
        id: "quad",
        channel: 4,
        label: "Mesa Boogie Quad",
        backgroundColor: "#0c0c0c",
        panelColor: "transparent",
        borderColor: "#ffffff",
        borderSize: 3,
        hasMultiSelection: true,
        stock: true,
        category: "amps",
        controllers: [
            // { label: "data", type: "LCD", message: false },
            { label: "rhythm1", note: 11, type: "TOGGLE", message: "CC", group: 1 },
            { label: "rhythm2", note: 12, type: "TOGGLE", message: "CC", group: 1 },
            { label: "lead1", note: 12, type: "TOGGLE", message: "CC", group: 1 },
            { label: "lead2", note: 12, type: "TOGGLE", message: "CC", group: 1 },
            { label: "eq1", note: 12, type: "TOGGLE", message: "CC", group: 2 },
            { label: "eq2", note: 12, type: "TOGGLE", message: "CC", group: 2 },
            { label: "reverb", note: 12, type: "TOGGLE", message: "CC", group: 2 },
        ],
    },
    {
        channel: 5,
        id: "pod",
        label: "Line6 Bass POD XT Pro",
        backgroundColor: "#070705",
        panelColor: "transparent",
        stock: true,
        category: "amps",
        controllers: [
            { label: "patch", type: "LCD", message: "PC", minValue: 1, maxValue: 64 },
            // { label: "data", type: "LCD", message: false },
            {
                note: 12,
                type: "ROTARY",
                message: "CC",
                group: 1,
                minValue: 0,
                maxValue: 28,
                label: "Amp Models",
            },
            {
                note: 71,
                type: "ROTARY",
                message: "CC",
                group: 1,
                minValue: 0,
                maxValue: 22,
                label: "Cab Models",
            },
            { label: "effects", note: 13, type: "ROTARY", message: "CC", group: 1 },
            { label: "drive", note: 13, type: "ROTARY", message: "CC", group: 2 },
            { label: "bass", note: 14, type: "ROTARY", message: "CC", group: 2 },
            {
                note: 15,
                type: "ROTARY",
                message: "CC",
                label: "Lo Mid",
                group: 2,
            },
            {
                note: 16,
                type: "ROTARY",
                message: "CC",
                label: "Hi Mid",
                group: 2,
            },
            {
                note: 17,
                type: "ROTARY",
                message: "CC",
                label: "Chan Vol",
                group: 2,
            },
            { label: "compress", note: 9, type: "ROTARY", message: "CC", group: 2 },
        ],
    },
    {
        channel: 5,
        id: "temp",
        label: "temp prova cancellazione",
        backgroundColor: "#070705",
        panelColor: "transparent",
        stock: false,
        category: "drums",
        controllers: [{ label: "patch", type: "LCD", message: "PC", minValue: 1, maxValue: 64 }],
    },
];

export default configs;
